monitoring:
  enabled: true
  metrics_collection_interval: 60  # seconds
  storage_path: "./collected_data"
  
event_analysis:
  pattern_recognition:
    enabled: true
    model_type: "classification"
    min_confidence: 0.85
    update_interval: 3600  # seconds
    
performance_optimization:
  enabled: true
  metrics:
    - execution_time
    - memory_usage
    - cpu_usage
  thresholds:
    execution_time_ms: 100
    memory_usage_mb: 50
    cpu_usage_percent: 80
    
data_collection:
  storage_format: "json"
  retention_period_days: 30
  compression: true
  
ml_models:
  pattern_recognition:
    type: "lstm"
    input_size: 64
    hidden_size: 128
    num_layers: 2
  performance_prediction:
    type: "xgboost"
    max_depth: 6
    learning_rate: 0.1